 export {Homepage } from "../pages/Homepage/Homepage";
 export { Mobilegames} from "../pages/mobilegamespage/Mobilegames";
 export { Aboutpage} from "../pages/aboutpage/Aboutpage";
 export { Contactpage} from "../pages/contactpage/Contactpage";
 export { Notfoundpage} from "../pages/notfoundpage/Notfoundpage";
 export { Createacountpage } from "./creatacountpage/Createacountpage";
 export { Loginpage }  from "../pages/loginpage/Loginpage";
 export {Searchbar} from "../pages/searchbar/Searchbar";
 export {Cardinfo}  from "../pages/cardinfo/cardinfo";
 export {GameDetails} from "./gamedetails/gamedetails";